// docker.js — runs the actual building inside Docker, streaming every
// line of output to the live log. Docker gives each build a clean,
// identical box — which is exactly what lets Perch scale to many sites
// (and, later, many servers) without surprises.

const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const logs = require('../logs/stream');

// Run any command and send its output to the deploy log, live.
function run(deployId, command, args, options = {}) {
  return new Promise((resolve, reject) => {
    logs.log(deployId, `$ ${command} ${args.join(' ')}`);
    const child = spawn(command, args, options);

    const pipe = (buf) =>
      buf
        .toString()
        .split('\n')
        .forEach((l) => l && logs.log(deployId, l));

    child.stdout.on('data', pipe);
    child.stderr.on('data', pipe);
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`command failed (exit ${code})`));
    });
  });
}

// Build a static / React project inside a clean Node container.
// Returns the folder that holds the finished files.
async function buildStatic(deployId, repoDir, plan) {
  // Install dependencies, then run the build — all inside node:20-alpine
  // (a small, fast Linux image with Node already on it).
  const install = 'if [ -f package-lock.json ]; then npm ci; else npm install; fi';
  const script = `${install} && ${plan.buildCommand}`;

  await run(deployId, 'docker', [
    'run', '--rm',
    '-v', `${repoDir}:/app`,
    '-w', '/app',
    'node:20-alpine',
    'sh', '-c', script,
  ]);

  return path.join(repoDir, plan.outputDir || 'dist');
}

// Build AND run a Next.js app (it needs a live server, not just files).
// We build a Docker image, then run it on a private port that Caddy
// will forward the public web address to.
async function buildAndRunNext(deployId, repoDir, site) {
  const image = `perch-${site.id}:latest`;
  const containerName = `perch-${site.id}`;

  // If the repo doesn't include its own Dockerfile, drop in a standard one.
  const dockerfile = path.join(repoDir, 'Dockerfile');
  if (!fs.existsSync(dockerfile)) {
    fs.writeFileSync(dockerfile, defaultNextDockerfile());
    logs.log(deployId, "No Dockerfile found — using Perch's default Next.js one.");
  }

  await run(deployId, 'docker', ['build', '-t', image, repoDir]);

  // Remove any old running copy (ignore errors if there isn't one).
  await run(deployId, 'docker', ['rm', '-f', containerName]).catch(() => {});

  // Run the new one. -p 127.0.0.1:PORT:3000 keeps it private; only
  // Caddy (on the same machine) can reach it.
  await run(deployId, 'docker', [
    'run', '-d',
    '--name', containerName,
    '--restart', 'unless-stopped',
    '-p', `127.0.0.1:${site.port}:3000`,
    image,
  ]);
}

function defaultNextDockerfile() {
  return `# Auto-generated by Perch for Next.js apps.
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
`;
}

module.exports = { run, buildStatic, buildAndRunNext };
